### ISSUE TITLE
Adjust 'Recurrent Neisserial infections' network plot

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#73]
# Tasks
## Difficulty: low
- [x] Determine why certain genes / diseases are missing
- [x] Omit  'Recurrent Neisserial infections' as a node in the network plot (since everything connects to it in this particular example)
## Difficulty: medium
- [x] Plot specificity of each gene as bar plot
## Difficulty: high
- [ ] ~~include variant-level information~~ beyond the scope of the study
> "We should be using this figure on a place to explain in more detail how and why all this works. We should show a gnomad-style plot for one of the genes showing where pathogenic variants with known clinical effects associated with the phenotype are located. We should also show the confidence level with which gene is associated with the trait." @NathanSkene 

![Screenshot 2024-06-15 at 13 21 54](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/6b3a653a-f886-40b4-beac-b57a2e57701d)

**Comment by bschilder** [comment]
##  Determine why certain genes / diseases are missing

This was actually due to a mapping issue between Disease IDs and the Disease Names. The HPO does not currently provide all of the disease names in their annotation files.

Instead, I had to write a new function to query their API thousands of times to collect this information. I've cached this ID-name map and have included a function that uses it to better map the disease names in the gene association data.

##  Omit 'Recurrent Neisserial infections' as a node in the network plot 

I think this is justified in this particular example, as the addition of the previously missing diseases and genes makes the network plot more complex. Removing RNI as a node reduces the number of plotted connections and makes it a bit easier to read. I also added connection from the disease to the gene (in addition from the disease to the cell type) to make the connection between "C7 deficiency" and the C7 gene more obvious.

Preview:

<img width="1260" alt="Screenshot 2024-06-15 at 13 30 40" src="https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/a7615ef8-fc9d-457c-82f8-29cf377c1f35">

**Comment by bschilder** [comment]
## Plot specificity of each gene as bar plot

I think this might work better as a heatmap underneath the network plot 
![image](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/1f07ce62-3ad2-4d2e-b64b-d95973d92e41)

**Comment by bschilder** [comment]
# include variant-level information
> "We should be using this figure on a place to explain in more detail how and why all this works. We should show a gnomad-style plot for one of the genes showing where pathogenic variants with known clinical effects associated with the phenotype are located. We should also show the confidence level with which gene is associated with the trait."

While I agree this could be helpful, gathering all of the information requested here is non-trivial.
Will circle back to this later.

**Comment by bschilder** [comment]
# include variant-level information

This is unfortunately beyond the scope of this study. It is not at all a trivial task to incorporate variant-level information. When I did this for a single gene in a single phenotype, it took me weeks to exact the information. This has not yet been automated.

Including variants in the figure also gives the false impression that we performed variant-level analyses.

**Comment by bschilder** [comment]
<img width="1284" alt="Screenshot 2024-09-24 at 13 31 55" src="https://github.com/user-attachments/assets/52b52a53-9ae5-4620-8c7d-062069bdceed">

- [ ] Add strength of evidence scores for RNI as another 1-row heatmap below the specificity heatmap

**Comment by bschilder** [comment]
# Updated version

Based on checklist [here](https://github.com/neurogenomics/rare_disease_celltyping/issues/73#issuecomment-2371143378).

![fig_network_rni](https://github.com/user-attachments/assets/ab52dc8f-1785-4f76-9a42-04cbed59a622)

**Comment by bschilder** [comment]
>  Need to know whether C7 is ONLY expressed in hepatoblasts (raw expression) so we can confidently make the claim that C7 is only relevant for hepatoblasts (amongst these cell types).

C7 is also expressed a bit in stromal cells, but not at all expressed in stratified epithelial cells and embryonic stem cells.

<img width="389" alt="Screenshot 2024-11-02 at 11 15 05 PM" src="https://github.com/user-attachments/assets/013e1f78-a675-4dcd-9185-72904a452373">
